In [5]:
import pandas as pd
import numpy as np

# creating pandas series from a list

In [140]:
countries_list=["USA","UK","New Zeland", "Australia","South Africa","Ireland","Srilanka","India"]

countries=pd.Series(data=countries_list)
print(countries)

0             USA
1              UK
2      New Zeland
3       Australia
4    South Africa
5         Ireland
6        Srilanka
7           India
dtype: object


- In the above output, right side values our data and left side data are index meaning they are way a to refrecnce our data 

- dtype indicates what is the type of our data and in here is is object (strings are considered as objects)

In [4]:
num=range(10)
data=pd.Series(data=num)
print(data)

0    0
1    1
2    2
3    3
4    4
5    5
6    6
7    7
8    8
9    9
dtype: int64


- Everything remains same but if you see the datatype now chages to integer64 meaning that each number is stored with 64 bits of memory

In [9]:
bool_data = np.random.rand(10) > .5
data=pd.Series(data=bool_data)
print(data)

0     True
1    False
2     True
3    False
4     True
5    False
6     True
7    False
8     True
9    False
dtype: bool


- Everything remains same but if you see the datatype now chages to boolean 

In [10]:
float_data=np.random.rand(10)
float_data=pd.Series(data=float_data)
print(float_data)

0    0.943967
1    0.096766
2    0.728376
3    0.414139
4    0.085329
5    0.349371
6    0.496197
7    0.818331
8    0.061047
9    0.821594
dtype: float64


- Everything remains same but if you see the datatype now chages to float64 bits 

- Note: We can also make the index to contains strings as well

In [13]:
float_data=np.random.rand(8)
float_data=pd.Series(data=float_data, index=countries_list)
print(float_data)

USA             0.135137
UK              0.739923
New Zeland      0.195243
Australia       0.463939
South Africa    0.604858
 Ireland        0.892661
Srilanka        0.545492
India           0.358394
dtype: float64


In [15]:
data={1: 'apple', 2: 'ball'}
fruits=pd.Series(data)
print(fruits)

1    apple
2     ball
dtype: object


- If we use dictionary for our data then keys will be acts as index and values will be act as our data.

# Series attributes 

- Series attributes ar nothing but the proeprties about our data such as what kind of data are we storing and length of our data and maximum/minimum values and etc.


# *data type*

In [19]:
fruits.dtype

dtype('O')

- dtype('O') meaning that its storing string values (Object)

In [21]:
float_data.dtype

dtype('float64')

- The above data is float data

# *Get the data as list*

In [23]:
fruits.values

array(['apple', 'ball'], dtype=object)

In [28]:
float_data.values

array([0.13513674, 0.73992296, 0.19524323, 0.46393851, 0.60485807,
       0.89266077, 0.54549185, 0.35839399])

In [27]:
type(float_data.values)

numpy.ndarray

- If we observe here, by using **values** proeprty we are getting an numpy array from the data. 

# *Get the index of the data*

- By using **index** property we can retrieve the index values from our data. If we didn't define custom index then we will get the numeric indices starting from 0 to length of our data

In [31]:
float_data.index

Index(['USA', 'UK', 'New Zeland', 'Australia', 'South Africa', ' Ireland',
       'Srilanka', 'India'],
      dtype='object')

In [34]:
countries.index

RangeIndex(start=0, stop=8, step=1)

- in the above Pandas series we didn't specify the index so we are getting numeric index by default.

# *Get the length of the data*

In [103]:
countries.size

8

# *Check whether all elements are unique or not.*

In [104]:
countries.is_unique

True

# *Check dimension of the data.*

In [131]:
countries.ndim

1

# *Check shape of the data.*

In [132]:
countries.shape

(8,)

# Series methods

- Similar to the attributes we have methods to perform on data such as fining sum or minimum or maximum among data and many other methods based on the requirement.

# *Finding sum of the data*

In [54]:
print(float_data)
print("**********")
print("sum of all elements are ",float_data.sum())

USA             0.135137
UK              0.739923
New Zeland      0.195243
Australia       0.463939
South Africa    0.604858
 Ireland        0.892661
Srilanka        0.545492
India           0.358394
dtype: float64
**********
sum of all elements are  3.935646118749841


# *Finding product of elements*

In [56]:
print(float_data.product())

0.0009560602264487872


# *Finding max of elements*

In [79]:
float_data.max()

0.8926607670763301

# *Finding product of elements*

In [105]:
float_data.min()

0.13513673665394288

# Attributes and methods combination

In [106]:
countries.str

- The above preoperty converts all strings to a method appply iterator. so that we can apply the string functions

In [107]:
countries.str.len()

0     3
1     2
2    10
3     9
4    12
5     8
6     8
7     5
dtype: int64

- The len() function will return the length of each string and the len() function will be applied to each and every string in the data

In [109]:
countries.str.upper()

0             USA
1              UK
2      NEW ZELAND
3       AUSTRALIA
4    SOUTH AFRICA
5         IRELAND
6        SRILANKA
7           INDIA
dtype: object

In [110]:
countries.str.strip()

0             USA
1              UK
2      New Zeland
3       Australia
4    South Africa
5         Ireland
6        Srilanka
7           India
dtype: object

# Methods and parameters


We can also pass the parameters to our functions so that we can pass required information before processing the data.

In [118]:
years=pd.read_csv(filepath_or_buffer='https://raw.githubusercontent.com/datasets/population/master/data/population.csv', usecols=["Year"], squeeze= True )

- In the above cell, we are reading the data from a file. If you notice here,

1. we passed the filepath so that it can read from specifed location.

2. we also pased which columns to use and which columns to not to use while reading

3. Passed Squazee=True, meaning that if in case we have only one colunmn thenn we are saying it to squazee it into an Series instead of dataframe

In [119]:
years

0        1960
1        1961
2        1962
3        1963
4        1964
5        1965
6        1966
7        1967
8        1968
9        1969
10       1970
11       1971
12       1972
13       1973
14       1974
15       1975
16       1976
17       1977
18       1978
19       1979
20       1980
21       1981
22       1982
23       1983
24       1984
25       1985
26       1986
27       1987
28       1988
29       1989
         ... 
14855    1987
14856    1988
14857    1989
14858    1990
14859    1991
14860    1992
14861    1993
14862    1994
14863    1995
14864    1996
14865    1997
14866    1998
14867    1999
14868    2000
14869    2001
14870    2002
14871    2003
14872    2004
14873    2005
14874    2006
14875    2007
14876    2008
14877    2009
14878    2010
14879    2011
14880    2012
14881    2013
14882    2014
14883    2015
14884    2016
Name: Year, Length: 14885, dtype: int64

In [121]:
years.index

RangeIndex(start=0, stop=14885, step=1)

In [122]:
years.is_unique

False

In [123]:
years.dtype

dtype('int64')

# Get the first n records from data 
- head() function returns top n records. By default it will give 5 rows. <br>

- It will take a parameter and return that many recods from data.

In [127]:
years.head()

0    1960
1    1961
2    1962
3    1963
4    1964
Name: Year, dtype: int64

In [128]:
years.head(10)

0    1960
1    1961
2    1962
3    1963
4    1964
5    1965
6    1966
7    1967
8    1968
9    1969
Name: Year, dtype: int64

# Get the last n records from data

- tail() function returns last n records. By default it will give 5 rows. <br>

- It will take a parameter and return that many recods from last in the data.

In [129]:
years.tail()

14880    2012
14881    2013
14882    2014
14883    2015
14884    2016
Name: Year, dtype: int64

In [130]:
years.tail(2)

14883    2015
14884    2016
Name: Year, dtype: int64

# *Sorting the data*

In [141]:
countries

0             USA
1              UK
2      New Zeland
3       Australia
4    South Africa
5         Ireland
6        Srilanka
7           India
dtype: object

In [142]:
countries.sort_values(inplace=True)

print(countries)

# countries.sort_values(
#     ascending=True,
#     inplace=False,
#     kind='quicksort',
#     na_position='last',
# )



3       Australia
7           India
5         Ireland
2      New Zeland
4    South Africa
6        Srilanka
1              UK
0             USA
dtype: object


- inplace = True indicates that store the sorted object in the same variabe 


In [143]:
countries.sort_values(ascending=False)

0             USA
1              UK
6        Srilanka
4    South Africa
2      New Zeland
5         Ireland
7           India
3       Australia
dtype: object

- By default sorting is in ascending order, to overcome that we have explicilty specify the ascending-=False

# *Sorting the data with index*

- We can also store the data using index as well. after sorting with data what if we want to get back to our own data then we can use the sort_index() to get back to previous object

In [145]:
countries.sort_index(inplace=True)
print(countries)

0             USA
1              UK
2      New Zeland
3       Australia
4    South Africa
5         Ireland
6        Srilanka
7           India
dtype: object


- Now, we have original series. so here you can observe when we sorting data, the respective index values are also moving like satelite data.

In [146]:
countries.sort_index(ascending=False)

7           India
6        Srilanka
5         Ireland
4    South Africa
3       Australia
2      New Zeland
1              UK
0             USA
dtype: object

# *Acessing the values inside the series*

In [147]:
countries[0]

'USA'

In [148]:
countries[0:2]

0    USA
1     UK
dtype: object

In [150]:
float_data

USA             0.135137
UK              0.739923
New Zeland      0.195243
Australia       0.463939
South Africa    0.604858
 Ireland        0.892661
Srilanka        0.545492
India           0.358394
dtype: float64

In [152]:
float_data[0:2]

USA    0.135137
UK     0.739923
dtype: float64

In [153]:
float_data["USA":"Srilanka"]

USA             0.135137
UK              0.739923
New Zeland      0.195243
Australia       0.463939
South Africa    0.604858
 Ireland        0.892661
Srilanka        0.545492
dtype: float64

In [154]:
float_data["USA":"Srilanka"].values

array([0.13513674, 0.73992296, 0.19524323, 0.46393851, 0.60485807,
       0.89266077, 0.54549185])

In [157]:
float_data[:-2].values

array([0.13513674, 0.73992296, 0.19524323, 0.46393851, 0.60485807,
       0.89266077])

In [161]:
float_data[["USA","UK","dsc"]]

USA    0.135137
UK     0.739923
dsc         NaN
dtype: float64

- Note: Even if the index not existed it will give an NaN but not an error.

- It will give an error when only one index using and if its not existed in data.

In [163]:
float_data['AS']

KeyError: 'AS'

In [165]:
float_data.get(key="AS",default="Missing")

'Missing'

- get() method is better that raw acessing because it provides a way to handle in case if the key is not exist in the data

In [168]:
sample=float_data.get(key=["USA","UK","AS"],default="Missing")
print(sample)

USA    0.135137
UK     0.739923
AS          NaN
dtype: float64


#  Return number of non-NA/null observations in the Series

In [175]:
sample.count()

2

#  Return number of observations in the Series

In [176]:
sample.size

3

# Get the 5-number summary 

In [179]:
float_data.describe()

count    8.000000
mean     0.491956
std      0.259573
min      0.135137
25%      0.317606
50%      0.504715
75%      0.638624
max      0.892661
dtype: float64

# Return the highest value index in data

In [188]:
float_data.idxmax()

' Ireland'

In [187]:
#return maximum values
float_data[float_data.idxmax()]

0.8926607670763301

# Return the highest value index in data

In [186]:
float_data.idxmin()

'USA'

In [189]:
#return minimum values
float_data[float_data.idxmin()]

0.13513673665394288

# groupby values

In [193]:
years_group=years.value_counts()
print(years_group)

2011    263
2006    263
2005    263
2007    263
2003    263
2010    263
2002    263
1998    263
2009    263
2001    263
2008    263
2000    263
1999    263
2004    263
2012    262
2016    262
1995    262
1996    262
2015    262
2014    262
1997    262
1990    262
1991    262
2013    262
1994    261
1992    261
1993    261
1973    260
1977    260
1967    260
1985    260
1975    260
1969    260
1961    260
1970    260
1983    260
1984    260
1976    260
1968    260
1962    260
1986    260
1978    260
1965    260
1982    260
1963    260
1971    260
1979    260
1987    260
1974    260
1966    260
1964    260
1972    260
1980    260
1988    260
1989    260
1981    260
1960    260
Name: Year, dtype: int64


In [197]:
type(years_group)

pandas.core.series.Series

In [202]:
years_group[-1:]

1960    260
Name: Year, dtype: int64

- value_counts() function returns a pandas series with values as key and occrence as value

In [203]:
years_group.sum()

14885

# Apply function 

- This function will apply to each instance in the data.

In [204]:
years.apply(lambda x: "before 1970" if x<1970 else "after 1970")

0        before 1970
1        before 1970
2        before 1970
3        before 1970
4        before 1970
5        before 1970
6        before 1970
7        before 1970
8        before 1970
9        before 1970
10        after 1970
11        after 1970
12        after 1970
13        after 1970
14        after 1970
15        after 1970
16        after 1970
17        after 1970
18        after 1970
19        after 1970
20        after 1970
21        after 1970
22        after 1970
23        after 1970
24        after 1970
25        after 1970
26        after 1970
27        after 1970
28        after 1970
29        after 1970
            ...     
14855     after 1970
14856     after 1970
14857     after 1970
14858     after 1970
14859     after 1970
14860     after 1970
14861     after 1970
14862     after 1970
14863     after 1970
14864     after 1970
14865     after 1970
14866     after 1970
14867     after 1970
14868     after 1970
14869     after 1970
14870     after 1970
14871     aft

# map function

- map() will apply on each instance and apply function to each instance.